---
- name: Copy web.html
  hosts: web
  #become: yes
  vars_files: vars/vars.yml
  tasks:
#   - name: httpd package is present
#     yum:
#      name: httpd
#      state: latest

#   - name: copy web.html
#     copy:
#      src: "{{ stage3 }}.html"
#      dest: /var/www/html/index.html

#   - name: httpd is started
#     service:
#      name: httpd
#      state: started
  
#   - name: checking return a status 200
#     uri:
#      url: http://10.184.0.7
#      return_content: true
#      status_code: 200
#     register: this
#     failed_when: "'db' not in this.content"

#   - name: debug
#     debug:
#      var: this

#   - name: debug
#     debug:
#      var: ansible_facts

  - name: check openport
    wait_for:
     host: 10.184.0.6
     port: "{{ item }}"
     state: started
     delay: 0
     timeout: 3
    with_items:
     - 443
     - 8080
     - 80
     - 21
     - 22

